# Day 1 phase 1

In [48]:
import pandas as pd
import numpy as np

In [49]:
import matplotlib.pyplot as plt

In [50]:
import seaborn as sns

In [51]:
users_path = "../data/raw/users.dat"
ratings_path = "../data/raw/ratings.dat"
movies_path = "../data/raw/movies.dat"

In [52]:
users  = pd.read_csv(
    users_path,
    sep = "::",
    engine = "python",
    header = None,
    names = ["user_id","gender","age","occupation","zip_code"]
)

In [53]:
users.head()

   user_id gender  age  occupation zip_code
0        1      F    1          10    48067
1        2      M   56          16    70072
2        3      M   25          15    55117
3        4      M   45           7    02460
4        5      M   25          20    55455

In [54]:
movies  = pd.read_csv(
    movies_path,
    sep = "::",
    engine = "python",
    header = None,
    names = ["movie_id","movie_name","genre"],
    encoding = "latin-1"
)

In [55]:
movies.head()

   movie_id                          movie_name                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [56]:
ratings = pd.read_csv(
    ratings_path,
    sep="::",
    engine="python",
    header=None,
    names=["user_id", "movie_id", "rating", "timestamp"]
)

In [57]:
ratings.head()

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [58]:
print("Users shape:", users.shape)
print("Movies shape:", movies.shape)
print("Ratings shape:", ratings.shape)

Users shape: (6040, 5)
Movies shape: (3883, 3)
Ratings shape: (1000209, 4)

In [59]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     6040 non-null   int64
 1   gender      6040 non-null   str
 2   age         6040 non-null   int64
 3   occupation  6040 non-null   int64
 4   zip_code    6040 non-null   str
dtypes: int64(3), str(2)
memory usage: 236.1 KB

In [60]:
users.describe()

           user_id          age   occupation
count  6040.000000  6040.000000  6040.000000
mean   3020.500000    30.639238     8.146854
std    1743.742145    12.895962     6.329511
min       1.000000     1.000000     0.000000
25%    1510.750000    25.000000     3.000000
50%    3020.500000    25.000000     7.000000
75%    4530.250000    35.000000    14.000000
max    6040.000000    56.000000    20.000000

In [61]:
ratings.describe()

            user_id      movie_id        rating     timestamp
count  1.000209e+06  1.000209e+06  1.000209e+06  1.000209e+06
mean   3.024512e+03  1.865540e+03  3.581564e+00  9.722437e+08
std    1.728413e+03  1.096041e+03  1.117102e+00  1.215256e+07
min    1.000000e+00  1.000000e+00  1.000000e+00  9.567039e+08
25%    1.506000e+03  1.030000e+03  3.000000e+00  9.653026e+08
50%    3.070000e+03  1.835000e+03  4.000000e+00  9.730180e+08
75%    4.476000e+03  2.770000e+03  4.000000e+00  9.752209e+08
max    6.040000e+03  3.952000e+03  5.000000e+00  1.046455e+09

In [62]:
users.isnull().sum()

user_id       0
gender        0
age           0
occupation    0
zip_code      0
dtype: int64

In [63]:
print("Duplicate users:", users.duplicated().sum())
print("Duplicate movies:", movies.duplicated().sum())
print("Duplicate ratings:", ratings.duplicated().sum())

Duplicate users: 0
Duplicate movies: 0
Duplicate ratings: 0

In [64]:
print("Unique users:", users["user_id"].nunique())
print("Unique movies:", movies["movie_id"].nunique())

print("Unique rating users:", ratings["user_id"].nunique())
print("Unique rating movies:", ratings["movie_id"].nunique())

Unique users: 6040
Unique movies: 3883
Unique rating users: 6040
Unique rating movies: 3706

In [65]:
print("Rating values:")
print(sorted(ratings["rating"].unique()))

print("\nMinimum rating:", ratings["rating"].min())
print("Maximum rating:", ratings["rating"].max())
print("Average rating:", ratings["rating"].mean())

Rating values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Minimum rating: 1
Maximum rating: 5
Average rating: 3.581564453029317

In [66]:
ratings_per_user = (
    ratings
    .groupby("user_id")
    .size()
)

ratings_per_user.head()

user_id
1     53
2    129
3     51
4     21
5    198
dtype: int64

In [67]:
print("Minimum ratings by a user:", ratings_per_user.min())
print("Maximum ratings by a user:", ratings_per_user.max())
print("Average ratings per user:", ratings_per_user.mean())

Minimum ratings by a user: 20
Maximum ratings by a user: 2314
Average ratings per user: 165.5975165562914

In [68]:
ratings_per_user.describe()

count    6040.000000
mean      165.597517
std       192.747029
min        20.000000
25%        44.000000
50%        96.000000
75%       208.000000
max      2314.000000
dtype: float64

In [69]:
ratings_per_movie = (
    ratings
    .groupby("movie_id")
    .size()
)

ratings_per_movie.describe()

count    3706.000000
mean      269.889099
std       384.047838
min         1.000000
25%        33.000000
50%       123.500000
75%       350.000000
max      3428.000000
dtype: float64

In [70]:
ratings_per_movie.sort_values(ascending=False).head(10)

movie_id
2858    3428
260     2991
1196    2990
1210    2883
480     2672
2028    2653
589     2649
2571    2590
1270    2583
593     2578
dtype: int64

In [71]:
ratings["datetime"] = pd.to_datetime(
    ratings["timestamp"],
    unit="s"
)

In [72]:
ratings[["timestamp", "datetime"]].head()

   timestamp            datetime
0  978300760 2000-12-31 22:12:40
1  978302109 2000-12-31 22:35:09
2  978301968 2000-12-31 22:32:48
3  978300275 2000-12-31 22:04:35
4  978824291 2001-01-06 23:38:11

In [73]:
print("Earliest rating:", ratings["datetime"].min())
print("Latest rating:", ratings["datetime"].max())

Earliest rating: 2000-04-25 23:05:32
Latest rating: 2003-02-28 17:49:50

In [74]:
print("Earliest rating:", ratings["datetime"].min())
print("Latest rating:", ratings["datetime"].max())

Earliest rating: 2000-04-25 23:05:32
Latest rating: 2003-02-28 17:49:50

In [75]:
rating_user_ids = set(ratings["user_id"])
user_ids = set(users["user_id"])

print("Users in ratings but not users table:",
      rating_user_ids - user_ids)

Users in ratings but not users table: set()

In [76]:
rating_movie_ids = set(ratings["movie_id"])
movie_ids = set(movies["movie_id"])

print("Movies in ratings but not movies table:",
      rating_movie_ids - movie_ids)

Movies in ratings but not movies table: set()

In [77]:
print("===== CARDINALITY =====")
print("Unique users:", users["user_id"].nunique())
print("Unique movies:", movies["movie_id"].nunique())
print("Unique rating users:", ratings["user_id"].nunique())
print("Unique rating movies:", ratings["movie_id"].nunique())

print("\n===== RATINGS =====")
print("Rating values:", sorted(ratings["rating"].unique()))
print("Minimum:", ratings["rating"].min())
print("Maximum:", ratings["rating"].max())
print("Average:", ratings["rating"].mean())

print("\n===== TIME RANGE =====")
print("Earliest:", ratings["datetime"].min())
print("Latest:", ratings["datetime"].max())

print("\n===== RELATIONSHIP CHECK =====")
print("Users missing from users table:",
      set(ratings["user_id"]) - set(users["user_id"]))

print("Movies missing from movies table:",
      set(ratings["movie_id"]) - set(movies["movie_id"]))

===== CARDINALITY =====
Unique users: 6040
Unique movies: 3883
Unique rating users: 6040
Unique rating movies: 3706

===== RATINGS =====
Rating values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Minimum: 1
Maximum: 5
Average: 3.581564453029317

===== TIME RANGE =====
Earliest: 2000-04-25 23:05:32
Latest: 2003-02-28 17:49:50

===== RELATIONSHIP CHECK =====
Users missing from users table: set()
Movies missing from movies table: set()

# DAY 1 phase 2

In [78]:
users_clean = users.copy()
movies_clean = movies.copy()
ratings_clean = ratings.copy()

In [79]:
ratings_clean["datetime"] = pd.to_datetime(
    ratings_clean["timestamp"],
    unit="s"
)

In [80]:
ratings_clean.dtypes

user_id              int64
movie_id             int64
rating               int64
timestamp            int64
datetime     datetime64[s]
dtype: object

In [81]:
ratings_clean["year"] = ratings_clean["datetime"].dt.year
ratings_clean["month"] = ratings_clean["datetime"].dt.month
ratings_clean["day"] = ratings_clean["datetime"].dt.day
ratings_clean["day_of_week"] = ratings_clean["datetime"].dt.day_name()

In [82]:
ratings_clean[
    ["timestamp", "datetime", "year", "month", "day", "day_of_week"]
].head()

   timestamp            datetime  year  month  day day_of_week
0  978300760 2000-12-31 22:12:40  2000     12   31      Sunday
1  978302109 2000-12-31 22:35:09  2000     12   31      Sunday
2  978301968 2000-12-31 22:32:48  2000     12   31      Sunday
3  978300275 2000-12-31 22:04:35  2000     12   31      Sunday
4  978824291 2001-01-06 23:38:11  2001      1    6    Saturday

In [83]:
movies_clean["genre"].str.split("|").head()

0     [Animation, Children's, Comedy]
1    [Adventure, Children's, Fantasy]
2                   [Comedy, Romance]
3                     [Comedy, Drama]
4                            [Comedy]
Name: genre, dtype: object

In [84]:
movies_clean["genre_list"] = movies_clean["genre"].str.split("|")

In [85]:
movies_clean[["movie_name", "genre", "genre_list"]].head()

,movie_name,genre,genre_list
0,Toy Story (1995),Animation|Children's|Comedy,"[Animation, Children's, Comedy]"
1,Jumanji (1995),Adventure|Children's|Fantasy,"[Adventure, Children's, Fantasy]"
2,Grumpier Old Men (1995),Comedy|Romance,"[Comedy, Romance]"
3,Waiting to Exhale (1995),Comedy|Drama,"[Comedy, Drama]"
4,Father of the Bride Part II (1995),Comedy,[Comedy]

In [86]:
ratings_clean.duplicated(
    subset=["user_id", "movie_id"]
).sum()

np.int64(0)

In [87]:
ratings_clean["rating"].value_counts().sort_index()

rating
1     56174
2    107557
3    261197
4    348971
5    226310
Name: count, dtype: int64

In [88]:
ratings_users = ratings_clean.merge(
    users_clean,
    on="user_id",
    how="left"
)

In [89]:
ratings_users.head()

,user_id,movie_id,rating,timestamp,datetime,year,month,day,day_of_week,gender,age,occupation,zip_code
0,1,1193,5,978300760,2000-12-31 22:12:40,2000,12,31,Sunday,F,1,10,48067
1,1,661,3,978302109,2000-12-31 22:35:09,2000,12,31,Sunday,F,1,10,48067
2,1,914,3,978301968,2000-12-31 22:32:48,2000,12,31,Sunday,F,1,10,48067
3,1,3408,4,978300275,2000-12-31 22:04:35,2000,12,31,Sunday,F,1,10,48067
4,1,2355,5,978824291,2001-01-06 23:38:11,2001,1,6,Saturday,F,1,10,48067

In [90]:
stream_data = ratings_users.merge(
    movies_clean,
    on="movie_id",
    how="left"
)

In [91]:
stream_data.head()

,user_id,movie_id,rating,timestamp,datetime,year,month,day,day_of_week,gender,age,occupation,zip_code,movie_name,genre,genre_list
0,1,1193,5,978300760,2000-12-31 22:12:40,2000,12,31,Sunday,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama,[Drama]
1,1,661,3,978302109,2000-12-31 22:35:09,2000,12,31,Sunday,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical,"[Animation, Children's, Musical]"
2,1,914,3,978301968,2000-12-31 22:32:48,2000,12,31,Sunday,F,1,10,48067,My Fair Lady (1964),Musical|Romance,"[Musical, Romance]"
3,1,3408,4,978300275,2000-12-31 22:04:35,2000,12,31,Sunday,F,1,10,48067,Erin Brockovich (2000),Drama,[Drama]
4,1,2355,5,978824291,2001-01-06 23:38:11,2001,1,6,Saturday,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy,"[Animation, Children's, Comedy]"

In [92]:
stream_data.shape

(1000209, 16)

In [93]:
stream_data.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp', 'datetime', 'year',
       'month', 'day', 'day_of_week', 'gender', 'age', 'occupation',
       'zip_code', 'movie_name', 'genre', 'genre_list'],
      dtype='str')

In [94]:
stream_data[
    [
        "user_id",
        "gender",
        "age",
        "occupation",
        "movie_id",
        "movie_name",
        "genre",
        "rating",
        "datetime"
    ]
].head(10)

,user_id,gender,age,occupation,movie_id,movie_name,genre,rating,datetime
0,1,F,1,10,1193,One Flew Over the Cuckoo's Nest (1975),Drama,5,2000-12-31 22:12:40
1,1,F,1,10,661,James and the Giant Peach (1996),Animation|Children's|Musical,3,2000-12-31 22:35:09
2,1,F,1,10,914,My Fair Lady (1964),Musical|Romance,3,2000-12-31 22:32:48
3,1,F,1,10,3408,Erin Brockovich (2000),Drama,4,2000-12-31 22:04:35
4,1,F,1,10,2355,"Bug's Life, A (1998)",Animation|Children's|Comedy,5,2001-01-06 23:38:11
5,1,F,1,10,1197,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,3,2000-12-31 22:37:48
6,1,F,1,10,1287,Ben-Hur (1959),Action|Adventure|Drama,5,2000-12-31 22:33:59
7,1,F,1,10,2804,"Christmas Story, A (1983)",Comedy|Drama,5,2000-12-31 22:11:59
8,1,F,1,10,594,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,4,2000-12-31 22:37:48
9,1,F,1,10,919,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,4,2000-12-31 22:22:48

In [95]:
import sqlite3
import pandas as pd

In [96]:
conn = sqlite3.connect("../streamsight.db")

In [98]:
users_clean.to_sql(
    "users",
    conn,
    if_exists="replace",
    index=False
)

movies_clean.drop(columns=["genre_list"]).to_sql(
    "movies",
    conn,
    if_exists="replace",
    index=False
)

ratings_clean.to_sql(
    "ratings",
    conn,
    if_exists="replace",
    index=False
)

1000209

In [99]:
pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

      name
0    users
1   movies
2  ratings

In [100]:
pd.read_sql(
    """
    SELECT COUNT(*) AS total_users
    FROM users;
    """,
    conn
)

   total_users
0         6040

In [102]:
stream_data.to_csv(
    "../data/raw/stream_data.csv",
    index=False
)